// Team Member Questionnaire — "We want to know ALL About you, but not in a creepy way!"
export const QUESTIONNAIRE_INTRO = "We want to know ALL About you, but not in a creepy way!";

export const QUESTIONNAIRE: { id: string; q: string }[] = [
  { id: "q1", q: "Where did you grow up?" },
  { id: "q2", q: "One childhood memory that shaped you:" },
  { id: "q3", q: "Are you close with your family? Who influences you most?" },
  { id: "q4", q: "Three words friends use to describe you:" },
  { id: "q5", q: "What gives you energy?" },
  { id: "q6", q: "What drains you?" },
  { id: "q7", q: "Introvert, extrovert, or mix?" },
  { id: "q8", q: "Something people misunderstand about you:" },
  { id: "q9", q: "What does a perfect day off look like?" },
  { id: "q10", q: "Morning, afternoon, or evening person?" },
  { id: "q11", q: "How do you unwind after a long day?" },
  { id: "q12", q: "What truly motivates you?" },
  { id: "q13", q: "Values that guide your decisions:" },
  { id: "q14", q: "A goal you're proud of:" },
  { id: "q15", q: "A dream few people know about:" },
  { id: "q16", q: "Preferred feedback style:" },
  { id: "q17", q: "How can someone support you when stressed?" },
  { id: "q18", q: "What does great leadership look like to you?" },
  { id: "q19", q: "What helps you feel connected to a team?" },
  { id: "q20", q: "Hobbies or passions outside work:" },
  { id: "q21", q: "Favorite music/artists:" },
  { id: "q22", q: "Favorite food/restaurants:" },
  { id: "q23", q: "Favorite sports teams:" },
  { id: "q24", q: "Favorite shows/movies:" },
  { id: "q25", q: "One unpopular opinion:" },
  { id: "q26", q: "Something difficult you've overcome:" },
  { id: "q27", q: "Best trip you've ever taken:" },
  { id: "q28", q: "Skill gained from past jobs:" },
  { id: "q29", q: "Biggest mentor in your life:" },
  { id: "q30", q: "Best version of you in 12 months:" },
  { id: "q31", q: "Personal goals right now:" },
  { id: "q32", q: "Something you'd like accountability for:" },
  { id: "q33", q: "Dogs, cats, or other?" },
  { id: "q34", q: "Go-to drink order:" },
  { id: "q35", q: "Favorite comfort meal:" },
  { id: "q36", q: "Three people you'd have dinner with:" },
  { id: "q37", q: "Something quirky or unique about you:" },
  { id: "q38", q: "Favorite holiday & why:" },
  { id: "q39", q: "A bucket list item:" },
  { id: "q40", q: "One thing we should know about you:" },
];
